---
title: "MT_data2"
output: html_document
---

```{r}
ts = as.numeric(read.csv("q2train.csv", as.is = TRUE)[,2])
plot(ts, type = 'l', main ="Figure1. Original Data Plot")
ts.log = log(ts)
plot(ts.log, type ="l", main = "Figure2. Log Data Plot")

ts.log.d = diff(ts.log)
plot(ts.log.d, type = 'l', main = "Figure3. Differenced Log Data")
acf(ts.log.d, lag.max = 100, main = "Figure4. ACF of Differenced Log Data")
# 52 is a large peak
pacf(ts.log.d, lag.max = 100, main = "Figure5. PACF of Differenced Log Data")

ts.log.dd = diff(ts.log.d, 52)
plot(ts.log.dd, type = 'l', main = "Figure6. Seasonal Differenced Log Data")
acf(ts.log.dd, lag.max = 120, main = "Figure7. ACF of Seasonal Differenced Log Data")$acf
# Large peak at lag 1 and 52, (48)
# MA(1), seasonal MA(1)
pacf(ts.log.dd, lag.max = 105, main = "Figure8. PACF of Seasonal Differenced Log Data")
# peaks at 52, there is a seasonal AR(1)
```

```{r}
m2112 = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 2), period = 52))
# Error message 
#Error in optim(init[mask], armafn, method = optim.method, hessian = TRUE,  : 
 # non-finite finite-difference value [4]

m2112_css = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 2), period = 52), method = "CSS")
tsdiag(m2112_css)
m2111_css = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 1), period = 52), method = "CSS")
tsdiag(m2111_css)
m3111_css = arima(ts.log, order = c(3, 1, 1), seasonal = list(order = c(1, 1, 1), period = 52), method = "CSS")
tsdiag(m3111_css)
m2113_css = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 3), period = 52), method = "CSS")
tsdiag(m2113_css)


computeCVmse_css <- function(order.totry, seasorder.totry){
  MSE <- numeric()
  for(k in 5:1){
    train.dt <-ts.log[1:(len - 52 * k)]
    test.dt <- ts.log[(len - 52 * k + 1):(len - 52 * (k - 1))]
    mod <- arima(train.dt, order = order.totry, seasonal = 
                   list(order = seasorder.totry, period = 52), method ="CSS")
    fcast <- predict(mod, n.ahead = 52)
    MSE[k] <- mean((exp(fcast$pred) - exp(test.dt))^2)
  }
  return(MSE)
}

MSE_m2112_css = computeCVmse_css(c(2, 1, 1), c(1,1,2))
MSE_m2111_css = computeCVmse_css(c(2, 1, 1), c(1,1,1))
MSE_m2113_css = computeCVmse_css(c(2, 1, 1), c(1,1,3))
MSE_m3111_css = computeCVmse_css(c(3, 1, 1), c(1,1,1))
MSE_m4111_css = computeCVmse_css(c(4, 1, 1), c(1,1,1))
MSE_m2211_css = computeCVmse_css(c(2, 1, 2), c(1,1,1))
MSE_m2121_css = computeCVmse_css(c(2, 1, 1), c(2,1,1))

MSE_m2112_css
# 10.812738 13.688074  5.465700  5.034556  7.155017
MSE_m2111_css
# 10.064929 13.953001  5.435703  4.974302  8.711411
MSE_m2113_css
# 10.836691 13.755722  5.238900  5.441690  7.317123
MSE_m3111_css
# 9.971862  14.113133  5.277065  4.921742  7.157777
MSE_m4111_css
# 10.073620 13.474610  5.173049  4.863462  9.355224
MSE_m2211_css
# 9.773860 12.552077  5.325432  4.898208 11.245692
MSE_m2121_css
#  9.642972 11.804532  5.313977  5.617547  8.846564
```

```{r}
m3111 = arima(ts.log, order = c(3, 1, 1), seasonal = list(order = c(1, 1, 1), period = 52), optim.method ="Nelder-Mead")
AIC(m3111)    #-1372.11
m2111_NM = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 1), period = 52), optim.method ="Nelder-Mead")
AIC(m2111_NM) #-1378.413
m2112_NM = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 2), period = 52), optim.method ="Nelder-Mead")
# Error in optim(init[mask], armafn, method = optim.method, hessian = TRUE,  : 
  #non-finite finite-difference value [4]
m2113_NM = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(1, 1, 3), period = 52), optim.method ="Nelder-Mead")
# Error in optim(init[mask], armafn, method = optim.method, hessian = TRUE,  : 
  #non-finite finite-difference value [4]
m2121_NM = arima(ts.log, order = c(2, 1, 1), seasonal = list(order = c(2, 1, 1), period = 52), optim.method ="Nelder-Mead", method ="ML")
# Error in optim(init[mask], armafn, method = optim.method, hessian = TRUE,  : 
  #function cannot be evaluated at initial parameters

```

```{r}
predictions = exp(predict(m2111, n.ahead = 104)$pred)

## Check: Does that make sense?
plot(1:(length(ts) + length(predictions)), c(ts, predictions), type = 'l', col = 1, main = "Prediction")
points((length(ts) + 1) : (length(ts) + length(predictions)), predictions, type = 'l', col = 2)


## Let's crete the file:
write.table(predictions,
            sep = ",",
            col.names = FALSE,
            row.names = FALSE,
            file = "Q2_Zhichao_Yang_25779475.txt")
            # file = "Q2_Zhichao_Yang_25779475.txt")

# A quick check, that the file is what we expect it to be:
read.table("Q2_Zhichao_Yang_25779475.txt", sep = ",")
plot(as.numeric(unlist(read.table("Q2_Zhichao_Yang_25779475.txt", sep = ","))), type ="l", main ="Figure 12 Prediction")


```

